### Question 1:
Write a program that calculates and prints the value according to the given formula:

Q = Square root of [(2 * C * D)/H]

Following are the fixed values of C and H:

C is 50. H is 30.

D is the variable whose values should be input to your program in a comma-separated sequence.

Example

Let us assume the following comma separated input sequence is given to the program:

100,150,180

The output of the program should be:

18,22,24

In [37]:
D=input()
l1=D.split(sep=",")
l=[]
for i in l1:
    i=int(i)
    Q = ((2 * 50 * i)/30)**(1/2)
    l.append(int(Q))
for j in l:
    if j==l[len(l)-1]:
        print(j)
    else:
         print(j,end=",")

100,150,180
18,22,24


### Question 2:
Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.

Note: i=0,1.., X-1; j=0,1,¡Y-1.

Example

Suppose the following inputs are given to the program:

3,5

Then, the output of the program should be:

[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]

In [56]:
import numpy as np
r=int(input("Enter number of rows"))
c=int(input("Enter number of columns"))
array= np.arange(c*r)
k=array.reshape(r,c)
print(k)

Enter number of rows3
Enter number of columns5
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


### Question 3:
Write a program that accepts a comma separated sequence of words as input and prints the

words in a comma-separated sequence after sorting them alphabetically.

Suppose the following input is supplied to the program:

without,hello,bag,world

Then, the output should be:

bag,hello,without,world

In [3]:
D=input()
l1=D.split(sep=",")
l1=sorted(l1)
for i in l1:
    if i==l1[len(l1)-1]:
        print(i)
    else:
        print(i,end=',')


without,hello,bag,world
bag,hello,without,world


### Question 4:
Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically.

Suppose the following input is supplied to the program:

hello world and practice makes perfect and hello world again

Then, the output should be:

again and hello makes perfect practice world

In [1]:
D=input()
l1=D.split(sep=" ")
l1=set(l1)
k=sorted(l1)
for i in k:
    if i==k[len(k)-1]:
        print(i)
    else:
        print(i,end=" ")

hello world and practice makes perfect and hello world again
again and hello makes perfect practice world


### Question 5:
Write a program that accepts a sentence and calculate the number of letters and digits.

Suppose the following input is supplied to the program:

hello world! 123

Then, the output should be:

LETTERS 10

DIGITS 3

In [9]:
p=input()
k=0
h=0
l=0
o="!@#$%^&*()_-+}{][|\"\'.,?"
for i in p:
    try:
        if i==" " or i in o :
            continue
        else:
            l=int(i)
            h+=1
    except:
        k+=1
print("LETTERS ",k)
print("DIGITS ",h)

hello world! 123
LETTERS  10
DIGITS  3


### Question 6:
A website requires the users to input username and password to register. Write a program to
check the validity of password input by users.

Following are the criteria for checking the password:

1. At least 1 letter between [a-z]

2. At least 1 number between [0-9]

1. At least 1 letter between [A-Z]

3. At least 1 character from [$#@]

4. Minimum length of transaction password: 6

5. Maximum length of transaction password: 12

Your program should accept a sequence of comma separated passwords and will check them
according to the above criteria. Passwords that match the criteria are to be printed, each
separated by a comma.

Example


If the following passwords are given as input to the program:

ABd1234@1F1#,2w3E*,2We3345

Then, the output of the program should be:

ABd1234@1


In [39]:
def Check_uppercase(n):
    inc=0
    up="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    for i in n:
        if i in up:
            inc+=1
    if inc>=1:
        return True
    else:
        return False
def Check_lowercase(n):
    inc=0
    up=("ABCDEFGHIJKLMNOPQRSTUVWXYZ").lower()
    for i in n:
        if i in up:
            inc+=1
    if inc>=1:
        return True
    else:
        return False
def Check_specialchar(n):
    inc=0
    up="$#@"
    for i in n:
        if i in up:
            inc+=1
    if inc>=1:
        return True
    else:
        return False
def Check_Number(n):
    inc=0
    up="1234567890"
    for i in n:
        if i in up:
            inc+=1
    if inc>=1:
        return True
    else:
        return False

In [57]:
ip=input("Enter password :")
inp=ip.split(sep=",")
l=""
le=[]
for j in inp:
    if len(j)>=6 and len(j)<=12:
            if  (Check_lowercase(j))==True and (Check_uppercase(j)==True) and (Check_specialchar(j)==True) and (Check_Number(j)==True):
                    le.append(j)
                    continue
            else:
                print("Password should contain :")
                print("1. At least 1 letter between [a-z]\n2. At least 1 number between [0-9]\n1. At least 1 letter between [A-Z]\n3. At least 1 character from [$#@]")
                break
            
    else:
        print("Password length should be in between 6 - 12 characters")
        break
for i in range(len(le)):
    if i==len(le)-1:
        print(le[i])
    else:
        print(le[i],end=",")

Enter password :ABd1234@1F1#,2w3E*,2We3345
Password length should be in between 6 - 12 characters
ABd1234@1F1#
